[[permission]]
identifier = "allow-get-help-text"
description = "Allows retrieving the application help text."
commands.allow = ["get_help_text"]

[[permission]]
identifier = "allow-launch-with-args"
description = "Allows re-launching the application with custom arguments."
commands.allow = ["launch_with_args"]
